[default.database]
POSTGRES_DB = "db"
POSTGRES_USER = "use"
POSTGRES_PASSWORD = "password"
POSTGRES_PORT = 5432
POSTGRES_HOST = "localhost"
POSTGRES_ASYNC_URL = "postgresql+asyncpg://user:password@localhost:5432/db"

[default.database.admin]
PGADMIN_DEFAULT_EMAIL = "pgadmin@example.com"
PGADMIN_DEFAULT_PASSWORD = "admin"
PGADMIN_PORT = 5050

[default.backend]
BACKEND_HOST = "backend"
BACKEND_PORT = 8000

[default.redis]
REDIS_HOST = "localhost"
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASSWORD = ""

[default.logging]
level = "INFO"
json_format = false
enable_console = true
enable_file = false
file_path = "logs/findar.log"

[default.grafana]
GF_SECURITY_ADMIN_USER = "admin"
GF_SECURITY_ADMIN_PASSWORD = "admin123"

[default.notifications]
TELEGRAM_BOT_TOKEN = "123456:ABC-DEF"
EMAIL_SMTP_USER = "smtp_user"
