# ===============================
# Pre-commit configuration
# ===============================
# Install:
#   uv pip install pre-commit
#   pre-commit install && pre-commit install -t pre-push
# Run manually:
#   git push --dry-run ${branch}
# Skip checks:
#   git commit --no-verify

fail_fast: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1 # Use the latest stable Ruff version
    hooks:
      - id: ruff-check
        args: [--fix, --exit-zero]
        stages: [pre-push]
      - id: ruff-format
        stages: [pre-push]

  - repo: https://github.com/crate-ci/typos
    rev: v1.38.1
    hooks:
      - id: typos
        stages: [pre-push]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [pre-push]
