services:
  api:
    build:
      context: .
      target: api
    container_name: api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    networks:
      - postgres
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrations:
        condition: service_started
    restart: unless-stopped

  migrations:
    build:
      context: .
      target: migrations
    container_name: migrations
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgres
    restart: "no"

  celery:
    build:
      context: .
      target: celery
    container_name: celery
    env_file:
      - .env
    networks:
      - postgres
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  bot:
    build:
      context: .
      target: bot
    container_name: bot
    env_file:
      - .env
    networks:
      - postgres
      - monitoring
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_started
    restart: unless-stopped

  frontend-builder:
    container_name: frontend-builder
    build:
      context: ./src/static/admiral
    volumes:
      - frontend_dist:/app/dist

  postgres:
    container_name: db
    image: postgres:16.10-alpine3.22
    volumes:
      - ./docker/postgresql.conf:/etc/postgresql.conf:ro
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    command: >
      postgres -c config_file=/etc/postgresql.conf
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 20G

  redis:
    image: redis/redis-stack:7.4.0-v7
    container_name: redis
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: >
      redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - postgres

  node-exporter:
    image: prom/node-exporter:v1.10.0
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)"
    ports:
      - "${NE_PORT}:9100"
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.7.1
    container_name: prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      node-exporter:
        condition: service_started

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - "${GF_PORT}:3000"
    networks:
      - monitoring
      - postgres
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
      postgres:
        condition: service_healthy

  loki:
    image: grafana/loki:3.5.7
    container_name: loki
    volumes:
      - ./docker/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "${LOKI_PORT}:3100"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started

  promtail:
    image: grafana/promtail:3.5.7
    container_name: promtail
    volumes:
      - ./docker/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: unless-stopped
    depends_on:
      - loki

  nginx-proxy:
    image: nginx:1.29.2-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./docker/confs/nginx:/etc/nginx/conf.d:ro

      # - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - postgres
      - monitoring
    depends_on:
      - api
      - frontend-builder
      - node-exporter
      - grafana
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data:
  prometheus_data:
  grafana_data:
  redis_data:
  loki_data:
  frontend_dist:

networks:
  postgres:
    driver: bridge
  monitoring:
    driver: bridge
