services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "${CADVISOR_PORT}:8080"
    networks:
      - monitoring
    restart: unless-stopped

  app:
    build: .
    container_name: app
    environment:
      - HOST=${HOST}
      - APP_PORT=${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - postgres
      - monitoring
    restart: unless-stopped

  celery:
    build: .
    container_name: celery
    command: >
      sh -c "
        echo '⏳ Waiting for dependencies...' &&
        sleep 5 &&
        uv run celery -A src.modules.queue.celery_config:celery_app worker
          --loglevel=info
          --queues=transactions,rule_executions,celery
          --pool=solo
      "
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "9091:9091"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - HOST=${HOST}
      - APP_PORT=${APP_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}/0
    networks:
      - postgres
      - monitoring

  frontend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./src/static/admiral:/app
      - frontend_dist:/app/dist
    command: sh -c "npm ci --legacy-peer-deps && npm run build"

  postgres:
    container_name: db
    image: postgres:16.10-alpine3.22
    volumes:
      - ./docker/postgresql.conf:/etc/postgresql.conf:ro
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    command: >
      postgres -c config_file=/etc/postgresql.conf
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 10G

  pgadmin:
    image: dpage/pgadmin4:9.9
    container_name: pgadmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False" # To allow running in desktop mode
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis/redis-stack:7.4.0-v7
    container_name: redis
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: >
      redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - postgres

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)"
    ports:
      - "${NE_PORT}:9100"
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.7.1
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - node-exporter
      - alertmanager
      - postgres

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "${GF_PORT}:3000"
    networks:
      - monitoring
      - postgres
    restart: unless-stopped
    depends_on:
      - prometheus
      - loki
      - postgres

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./docker/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "${LOKI_PORT}:3100"
    restart: unless-stopped
    depends_on:
      - postgres

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./docker/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      # - /var/log:/var/log   # если логируем хостовые логи
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: unless-stopped
    depends_on:
      - loki

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    volumes:
      - ./monitoring/alertmanager:/etc/alertmanager
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "${AM_PORT}:9093"
    networks:
      - monitoring
    restart: unless-stopped

  nginx-proxy:
    image: nginx:1.29.2-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./docker/confs/nginx:/etc/nginx/conf.d:ro

      # - ./nginx/certs:/etc/nginx/certs:ro
    # networks:
    #   - postgres
    #   - monitoring
    restart: unless-stopped

volumes:
  db_data:
  pgadmin_data:
  prometheus_data:
  grafana_data:
  redis_data:
  loki_data:
  frontend_dist:

networks:
  postgres:
    driver: bridge
  monitoring:
    driver: bridge
