"""added new fields to transactions

Revision ID: 5443b6bc781d
Revises: a0149c5e906d
Create Date: 2025-10-25 12:46:10.924869

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5443b6bc781d"
down_revision: Union[str, Sequence[str], None] = "a0149c5e906d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('celery_taskmeta')
    # op.drop_table('celery_tasksetmeta')
    op.add_column(
        "transactions", sa.Column("reviewed_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "transactions",
        sa.Column("review_comment", sqlmodel.AutoString(length=1000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "review_comment")
    op.drop_column("transactions", "reviewed_at")
    # op.create_table('celery_tasksetmeta',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('taskset_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('celery_tasksetmeta_pkey')),
    # sa.UniqueConstraint('taskset_id', name=op.f('celery_tasksetmeta_taskset_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # op.create_table('celery_taskmeta',
    # sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('task_id', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    # sa.Column('result', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('date_done', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('traceback', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('name', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.Column('args', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('kwargs', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.Column('worker', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('queue', sa.VARCHAR(length=155), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('celery_taskmeta_pkey')),
    # sa.UniqueConstraint('task_id', name=op.f('celery_taskmeta_task_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    # )
    # ### end Alembic commands ###
