name: prettier
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: "--check **/*.{yml,yaml,json,md,toml}"
          prettier_config_path: ".prettierrc.yaml"
          only_changed: false
